In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
from sklearn import datasets

In [67]:
iris=datasets.load_iris()

In [50]:
print('iris 키', iris.keys())

iris 키 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [53]:
print('데이터:\n', iris['data'][:5])

데이터:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [65]:
print('특성 이름:', iris['feature_names'])

특성 이름: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [66]:
print('타깃 이름:', iris['target_names'])

타깃 이름: ['setosa' 'versicolor' 'virginica']


In [59]:
print('데이터 크키:', iris['data'].shape)

데이터 크키: (150, 4)


In [60]:
print('타깃 크기:', iris['target'].shape)

타깃 크기: (150,)


In [77]:
from sklearn.model_selection import train_test_split

In [81]:
X_train, X_test, y_train, y_test = train_test_split(iris['data'],iris['target'], random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(112, 4) (112,)
(38, 4) (38,)


In [84]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [85]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [93]:
import numpy as np

X_new = np.array([[6,3.5,5,1.5]])

In [94]:
y_pred = knn.predict(X_test)

In [97]:
print('테스트 세트 예측 값:\n', y_pred)
print('테스트 세트 실제 타깃:\n', y_test)

테스트 세트 예측 값:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
테스트 세트 실제 타깃:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


In [100]:
print(f"훈련 세트 정확도: {knn.score(X_train, y_train):3f}")
print(f'테스트 세트 정확도: {knn.score(X_test, y_test):3f}')

훈련 세트 정확도: 0.964286
테스트 세트 정확도: 0.973684
